dist: xenial
language: ruby
cache:
  bundler: true
addons:
  apt:
    packages:
    - hunspell
    - libhunspell-dev
    - hunspell-en-us
rvm:
- 2.5.3
git:
  depth: 1
branches:
  only: develop
before_install:
- git config --global submodule.recurse true
- git config --global submodule.fetchJobs 8
before_deploy:
- bundle exec rake spell_check
- openssl aes-256-cbc -K $encrypted_b0cfc79abf17_key -iv $encrypted_b0cfc79abf17_iv
  -in _keys/deploy_rsa.enc -out /tmp/deploy_rsa -d
- openssl aes-256-cbc -K $encrypted_b0cfc79abf17_key -iv $encrypted_b0cfc79abf17_iv
  -in _keys/deploy_grader.enc -out /tmp/deploy_grader -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- chmod 600 /tmp/deploy_grader
deploy:
  provider: script
  script: bash _scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: develop
