dist: xenial
language: ruby
cache:
  bundler: true
  directories:
    - .jekyll-cache
addons:
  apt:
    packages:
    - hunspell
    - libhunspell-dev
    - hunspell-en-us
rvm:
- 2.6
git:
  depth: 1
branches:
  only: develop
before_deploy:
- bundle exec rake spell_check
- gpg --passphrase $pradyumna_gpg_passphrase --output /tmp/dual_deploy_key --decrypt pradyumna-dual-deploy.enc 
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/dual_deploy_key
deploy:
  provider: script
  script: bash _scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: develop
