# Site settings
title: "CS 241: System Programming"
email: angrave@illinois.edu
description: > # this means to ignore newlines until "baseurl:"
  Webpage for CS 241: System Programming at the University of Illinois Urbana-Champaign.
  All documentation and information about the course can be found here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://illinois-cs241.github.io" # the base hostname & protocol for your site
repository: illinois-cs241/illinois-cs241.github.io
docs_repository: illinois-cs241/assignment-docs
github_username: illinois-cs241
# Settings for the course
# semester is generated automagically
course_number: "241"
subject_code: "cs"
course_name: "System Programming"
exclude:
  [
    ".git",
    "README.md",
    "deploy_rsa.enc",
    "vendor",
    "bundle",
    "wp_repo",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "Rakefile",
    "_docs/deploy_rsa.enc",
    "_docs/deploy.sh",
    "_docs/retry.sh",
    "_docs/cleanup.sh",
  ]
navbar_items:
  - name: "Assignments"
    link: "/assignments.html"
    sublinks:
      - name: "Grade Viewer"
        link: "https://sp19-cs241-grd-02.cs.illinois.edu/grades"
      - name: "Broadway On-Demand Autograder"
        link: "https://sp19-cs241-grd-02.cs.illinois.edu/on-demand/"
  - name: "Quizzes"
    link: "/quiz_topics.html"
  - name: "Help!"
    link: "/help.html"
  - name: "Schedule"
    link: "/schedule.html"
    sublinks:
      - name: "Lectures"
        link: "https://classtranscribe.illinois.edu/"
  - name: "Honors"
    link: "/honors.html"
  - name: "Staff"
    link: "/staff.html"
    sublinks:
      - name: "Staff Hall of Fame"
        link: "/staff_hall_of_fame.html"
  - name: "Coursebook"
    link: "/coursebook/index.html"
  - name: "Links"
    link: "/links.html"
# Settings for docs collection
collections:
  docs:
    output: true
    permalink: /assignments/:path
  pages:
    output: true
    permalink: /:path
  resources:
    output: true
    permalink: /resources/:path
  coursebook:
    output: true
    permalink: /coursebook/:path
  tutorials:
    output: true
    permalink: /tutorials/:path
  slides:
    output: true
    permalink: /slides/:path
# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
reveal:
  css_url: "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0/css/reveal.css"
  css_theme_url: "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0/css/theme/black.css"
  css_syntax_url: "/css/reveal-code-style.css"
  lib_head_url: "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0/lib/js/head.min.js"
  reveal_js_url: "https://cdnjs.cloudflare.com/ajax/libs/reveal.js/3.7.0/js/reveal.js"
plugins_dir:
  - _plugins
